"""create domain_events and file_list_view tables

Revision ID: 3af924cc45ef
Revises:
Create Date: 2026-03-07 09:56:39.760744

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3af924cc45ef"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # -- domain_events: 統合イベントストア --
    # すべてのドメインイベント (アップロード Hook、将来の変換イベント等) を
    # イミュータブルなログとして記録する。event_id がグローバルシーケンスとなり、
    # SSE の Last-Event-ID としても利用される。
    op.create_table(
        "domain_events",
        # グローバルシーケンス (SSE id としても使用)
        sa.Column("event_id", sa.Integer(), autoincrement=True, nullable=False),
        # 集約の識別子 (= upload_id)
        sa.Column("stream_id", sa.Text(), nullable=False),
        # ストリーム種別: "upload" / "conversion" (将来)
        sa.Column("stream_type", sa.Text(), nullable=False),
        # イベント種別: "hook.pre-create", "hook.post-finish",
        #   "conversion.started", "conversion.completed" (将来) 等
        sa.Column("event_type", sa.Text(), nullable=False),
        # イベント発生日時 (ISO 8601, SQLite server_default)
        sa.Column(
            "occurred_at",
            sa.Text(),
            server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%f', 'now'))"),
            nullable=False,
        ),
        # HookRequest 等の JSON シリアライズ
        sa.Column("payload", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "idx_domain_events_event_type", "domain_events", ["event_type"], unique=False
    )
    op.create_index(
        "idx_domain_events_occurred_at", "domain_events", ["occurred_at"], unique=False
    )
    op.create_index(
        "idx_domain_events_stream_id", "domain_events", ["stream_id"], unique=False
    )
    op.create_index(
        "idx_domain_events_stream_type", "domain_events", ["stream_type"], unique=False
    )

    # -- file_list_view: 射影テーブル --
    # domain_events から Projector が導出するファイル一覧用のマテリアライズドビュー。
    # REST API (GET /files) はこのテーブルを直接クエリする。
    op.create_table(
        "file_list_view",
        # tusd が割り当てるアップロード ID (= domain_events.stream_id)
        sa.Column("upload_id", sa.Text(), nullable=False),
        # Projector が導出する表示用ステータス
        #   "creating" / "created" / "uploading" / "finishing" / "uploaded" /
        #   "terminating" / "terminated" / "converting" (将来) / "ready" (将来)
        sa.Column("display_status", sa.Text(), nullable=False),
        # アップロードファイルのサイズ (bytes)
        sa.Column("file_size", sa.Integer(), nullable=True),
        # 現在のアップロード済みオフセット (bytes)
        sa.Column("file_offset", sa.Integer(), nullable=True),
        # クライアントが指定したファイル名 (metaData.filename)
        sa.Column("filename", sa.Text(), nullable=True),
        # クライアントが指定したファイル種別 (metaData.filetype)
        sa.Column("filetype", sa.Text(), nullable=True),
        # tusd metaData の JSON 文字列
        sa.Column("metadata", sa.Text(), nullable=True),
        # tusd storage 情報の JSON 文字列
        sa.Column("storage", sa.Text(), nullable=True),
        # アップロード元のリモートアドレス
        sa.Column("remote_addr", sa.Text(), nullable=True),
        # 変換ジョブの状態サマリ JSON 配列 (将来用, 初期は NULL)
        sa.Column("conversion_summary", sa.Text(), nullable=True),
        # 最後に処理した domain_events.event_id
        sa.Column("last_event_id", sa.Integer(), nullable=False),
        # レコード作成日時 (ISO 8601, アプリケーション側で設定)
        sa.Column("created_at", sa.Text(), nullable=False),
        # レコード更新日時 (ISO 8601)
        sa.Column(
            "updated_at",
            sa.Text(),
            server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%f', 'now'))"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["last_event_id"],
            ["domain_events.event_id"],
        ),
        sa.PrimaryKeyConstraint("upload_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file_list_view")
    op.drop_index("idx_domain_events_stream_type", table_name="domain_events")
    op.drop_index("idx_domain_events_stream_id", table_name="domain_events")
    op.drop_index("idx_domain_events_occurred_at", table_name="domain_events")
    op.drop_index("idx_domain_events_event_type", table_name="domain_events")
    op.drop_table("domain_events")
    # ### end Alembic commands ###
