"""create upload_events and upload_snapshots tables

Revision ID: cef0eda28b85
Revises:
Create Date: 2026-03-07 07:44:25.300998

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cef0eda28b85"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "upload_events",
        sa.Column("event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("upload_id", sa.Text(), nullable=False),
        sa.Column("hook_type", sa.Text(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.Text(),
            server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%f', 'now'))"),
            nullable=False,
        ),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "idx_upload_events_hook_type", "upload_events", ["hook_type"], unique=False
    )
    op.create_index(
        "idx_upload_events_occurred_at", "upload_events", ["occurred_at"], unique=False
    )
    op.create_index(
        "idx_upload_events_upload_id", "upload_events", ["upload_id"], unique=False
    )
    op.create_table(
        "upload_snapshots",
        sa.Column("upload_id", sa.Text(), nullable=False),
        sa.Column("current_status", sa.Text(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("file_offset", sa.Integer(), nullable=True),
        sa.Column("size_is_deferred", sa.Integer(), nullable=True),
        sa.Column("is_partial", sa.Integer(), nullable=True),
        sa.Column("is_final", sa.Integer(), nullable=True),
        sa.Column("filename", sa.Text(), nullable=True),
        sa.Column("filetype", sa.Text(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.Column("storage", sa.Text(), nullable=True),
        sa.Column("remote_addr", sa.Text(), nullable=True),
        sa.Column("last_hook_type", sa.Text(), nullable=False),
        sa.Column("last_event_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.Text(),
            server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%f', 'now'))"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["last_event_id"],
            ["upload_events.event_id"],
        ),
        sa.PrimaryKeyConstraint("upload_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("upload_snapshots")
    op.drop_index("idx_upload_events_upload_id", table_name="upload_events")
    op.drop_index("idx_upload_events_occurred_at", table_name="upload_events")
    op.drop_index("idx_upload_events_hook_type", table_name="upload_events")
    op.drop_table("upload_events")
    # ### end Alembic commands ###
